version: "3"
services:
 db:
  image: postgres:latest
  container_name: postgres
  restart: always
  ports:
   - "5432:5432"
  environment:
   POSTGRES_USER: "user"
   POSTGRES_PASSWORD: "1234"
   POSTGRES_DB: "user"
 redis:
  image: redis:latest
  command: redis-server --requirepass "1234" --port 6379
  container_name: redis
  labels:
   - "name=redis"
   - "mode=standalone"
  ports:
   - 6379:6379
